#!/bin/bash
# Полная установка и запуск проекта - выполните эти команды по порядку

echo "=========================================="
echo "Установка ПрофСпортСРМ на Kali Linux"
echo "=========================================="
echo ""
echo "Выполните следующие команды по порядку:"
echo ""
echo "1. Установка npm:"
echo "   sudo apt update"
echo "   sudo apt install -y npm"
echo ""
echo "2. Запуск PostgreSQL:"
echo "   sudo systemctl start postgresql"
echo "   sudo systemctl enable postgresql"
echo ""
echo "3. Создание базы данных:"
echo "   sudo -u postgres psql"
echo ""
echo "   В консоли PostgreSQL выполните:"
echo "   CREATE DATABASE martial_arts_crm;"
echo "   CREATE USER crm_user WITH PASSWORD '0408';"
echo "   GRANT ALL PRIVILEGES ON DATABASE martial_arts_crm TO crm_user;"
echo "   \\c martial_arts_crm"
echo "   GRANT ALL ON SCHEMA public TO crm_user;"
echo "   \\q"
echo ""
echo "4. После выполнения шагов 1-3, запустите:"
echo "   ./quick_start.sh"
echo ""
echo "Или выполните вручную:"
echo "   npm install"
echo "   cd client && npm install && cd .."
echo "   npx prisma generate"
echo "   npx prisma migrate dev"
echo "   npx prisma db seed"
echo "   npm run dev"
echo ""

